### ISSUE TITLE
Bowtie2 lib dependency breaks

### ISSUE THREAD

**Issue by saramonzon** [GuilleGorines/nfcore-pikavirus#3]
https://github.com/GuilleGorines/nfcore-pikavirus/blob/d7cfa0745d13c046b8279979b1eb8542d6d3d2ba/environment.yml#L25

At some point the tbb library for conda is broken so you need to add:
- tbb=2020.2 

to your environment.yml

**Comment by GuilleGorines** [comment]
Fixed on commit 03d22f84709915d0faf69787d228ad3a18569bb7 !

Thank you for your attention!
